
			<p>Перечень допустимых символов:
			<ul>
				<li>строчные буквы латинского алфавита;</li>
				<li>цифры «<span class="sym">0</span>» и «<span class="sym">1</span>»;</li>
				<li>символы «<span class="sym">~</span>», «<span class="sym">!</span>», «<span class="sym">/</span>», «<span class="sym">\</span>», «<span class="sym">&amp;</span>», «<span class="sym">*</span>», «<span class="sym">|</span>», «<span class="sym">+</span>», «<span class="sym">^</span>», «<span class="sym">&gt;</span>», «<span class="sym">&lt;</span>», «<span class="sym">=</span>», «<span class="sym">(</span>», «<span class="sym">)</span>».</li>
			</ul>
			<p>Обозначения, принятые в логическом калькуляторе:
			<ul>
				<li>переменные: строчные буквы латинского алфавита;</li>
				<li>константы: «<span class="sym">0</span>» (ложь) и «<span class="sym">1</span>» (истина);</li>
				<li>логические операции в порядке уменьшения приоритета:
					<ul>
						<li>
							<details>
								<summary>логическое отрицание: «<span class="sym">~</span>» или «<span class="sym">!</span>», приоритет 1;</summary>
								<table>
									<tbody>
										<tr>
											<th>x</th><th>¬x</th>
										</tr>
										<tr>
											<td>0</td><td>1</td>
										</tr>
										<tr>
											<td>1</td><td>0</td>
										</tr>
									</tbody>
								</table>
							</details>
						</li>
						<li>
							<details>
								<summary>штрих Шеффера: «<span class="sym">/</span>», приоритет 2;</summary>
								<table>
									<tbody>
										<tr>
											<th>x</th><th>y</th><th>x↑y</th>
										</tr>
										<tr>
											<td>0</td><td>0</td><td>1</td>
										</tr>
										<tr>
											<td>0</td><td>1</td><td>1</td>
										</tr>
										<tr>
											<td>1</td><td>0</td><td>1</td>
										</tr>
										<tr>
											<td>1</td><td>1</td><td>0</td>
										</tr>
									</tbody>
								</table>
							</details>
						</li>
						<li>
							<details>
								<summary>стрелка Пирса: «<span class="sym">\</span>», приоритет 2;</summary>
								<table>
									<tbody>
										<tr>
											<th>x</th><th>y</th><th>x↓y</th>
										</tr>
										<tr>
											<td>0</td><td>0</td><td>1</td>
										</tr>
										<tr>
											<td>0</td><td>1</td><td>0</td>
										</tr>
										<tr>
											<td>1</td><td>0</td><td>0</td>
										</tr>
										<tr>
											<td>1</td><td>1</td><td>0</td>
										</tr>
									</tbody>
								</table>
							</details>
						</li>
						<li>
							<details>
								<summary>конъюнкция: «<span class="sym">&amp;</span>» или «<span class="sym">*</span>», приоритет 3;</summary>
								<table>
									<tbody>
										<tr>
											<th>x</th><th>y</th><th>x∧y</th>
										</tr>
										<tr>
											<td>0</td><td>0</td><td>0</td>
										</tr>
										<tr>
											<td>0</td><td>1</td><td>0</td>
										</tr>
										<tr>
											<td>1</td><td>0</td><td>0</td>
										</tr>
										<tr>
											<td>1</td><td>1</td><td>1</td>
										</tr>
									</tbody>
								</table>
							</details>
						</li>
						<li>
							<details>
								<summary>дизъюнкция: «<span class="sym">|</span>» или «<span class="sym">+</span>», приоритет 4;</summary>
								<table>
									<tbody>
										<tr>
											<th>x</th><th>y</th><th>x∨y</th>
										</tr>
										<tr>
											<td>0</td><td>0</td><td>0</td>
										</tr>
										<tr>
											<td>0</td><td>1</td><td>1</td>
										</tr>
										<tr>
											<td>1</td><td>0</td><td>1</td>
										</tr>
										<tr>
											<td>1</td><td>1</td><td>1</td>
										</tr>
									</tbody>
								</table>
							</details>
						</li>
						<li>
							<details>
								<summary>неравнозначность: «<span class="sym">^</span>», приоритет 4;</summary>
								<table>
									<tbody>
										<tr>
											<th>x</th><th>y</th><th>x⊕y</th>
										</tr>
										<tr>
											<td>0</td><td>0</td><td>0</td>
										</tr>
										<tr>
											<td>0</td><td>1</td><td>1</td>
										</tr>
										<tr>
											<td>1</td><td>0</td><td>1</td>
										</tr>
										<tr>
											<td>1</td><td>1</td><td>0</td>
										</tr>
									</tbody>
								</table>
							</details>
						</li>
						<li>
							<details>
								<summary>импликация: «<span class="sym">&gt;</span>», приоритет 5;</summary>
								<table>
									<tbody>
										<tr>
											<th>x</th><th>y</th><th>x→y</th>
										</tr>
										<tr>
											<td>0</td><td>0</td><td>1</td>
										</tr>
										<tr>
											<td>0</td><td>1</td><td>1</td>
										</tr>
										<tr>
											<td>1</td><td>0</td><td>0</td>
										</tr>
										<tr>
											<td>1</td><td>1</td><td>1</td>
										</tr>
									</tbody>
								</table>
							</details>
						</li>
						<li>
							<details>
								<summary>обратная импликация: «<span class="sym">&lt;</span>», приоритет 5;</summary>
								<table>
									<tbody>
										<tr>
											<th>c</th><th>y</th><th>x←y</th>
										</tr>
										<tr>
											<td>0</td><td>0</td><td>1</td>
										</tr>
										<tr>
											<td>0</td><td>1</td><td>0</td>
										</tr>
										<tr>
											<td>1</td><td>0</td><td>1</td>
										</tr>
										<tr>
											<td>1</td><td>1</td><td>1</td>
										</tr>
									</tbody>
								</table>
							</details>
						</li>
						<li>
							<details>
								<summary>эквиваленция: «<span class="sym">=</span>», приоритет 6;</summary>
								<table>
									<tbody>
										<tr>
											<th>x</th><th>y</th><th>x↔y</th>
										</tr>
										<tr>
											<td>0</td><td>0</td><td>1</td>
										</tr>
										<tr>
											<td>0</td><td>1</td><td>0</td>
										</tr>
										<tr>
											<td>1</td><td>0</td><td>0</td>
										</tr>
										<tr>
											<td>1</td><td>1</td><td>1</td>
										</tr>
									</tbody>
								</table>
							</details>
						</li>
					</ul>
				</li>
				<li>скобки «<span class="sym">(</span>» и «<span class="sym">)</span>» для изменения приоритета операций.</li>
			</ul>